#!/bin/bash

declare -A VOICES
VOICES=(
	['Nicole']=1
	['Enrique']=1
	['Tatyana']=1
	['Russell']=1
	['Lotte']=1
	['Geraint']=1
	['Carmen']=1
	['Mads']=1
	['Penelope']=1
	['Mia']=1
	['Joanna']=1
	['Matthew']=1
	['Brian']=1
	['Seoyeon']=1
	['Ruben']=1
	['Ricardo']=1
	['Maxim']=1
	['Lea']=1
	['Giorgio']=1
	['Carla']=1
	['Naja']=1
	['Maja']=1
	['Astrid']=1
	['Ivy']=1
	['Kimberly']=1
	['Chantal']=1
	['Amy']=1
	['Vicki']=1
	['Marlene']=1
	['Ewa']=1
	['Conchita']=1
	['Karl']=1
	['Zeina']=1
	['Miguel']=1
	['Mathieu']=1
	['Justin']=1
	['Lucia']=1
	['Jacek']=1
	['Bianca']=1
	['Takumi']=1
	['Ines']=1
	['Gwyneth']=1
	['Cristiano']=1
	['Mizuki']=1
	['Celine']=1
	['Zhiyu']=1
	['Jan']=1
	['Liv']=1
	['Joey']=1
	['Raveena']=1
	['Filiz']=1
	['Dora']=1
	['Salli']=1
	['Aditi']=1
	['Vitoria']=1
	['Emma']=1
	['Hans']=1
	['Kendra']=1
)
readonly VOICES

usage() {
	echo -e "Usage:  tts [-h] [-v VOICE] [-d FILENAME|-p] <text_to_speak>"
}

# Read arguments
declare COMMAND VOICE TEXT
COMMAND=DOWNLOAD
VOICE=Brian
OUTPUT="./tts-$(date '+%s').ogg"
while getopts ":ld:pv:h" OPT; do
	case "$OPT" in
	h)
		usage
		printf "Converts text to speech using the StreamLabs API\n"
		printf "Any other positional arguments are interpreted as the text input\n"
		printf "If no text is present, reads from STDIN\n\n"
		printf "   -h           Prints this help message and exits\n"
		printf "   -v VOICE     Change the voice used for TTS\n"
		printf "   -l           List available voices\n"
		printf "   -d FILENAME  Download the .ogg file to FILENAME.ogg [default]\n"
		printf "   -p           Instead of downloading, print the audio URL\n"
		printf "\nDisclaimer: Not affiliated or endorsed by StreamLabs\n"
		exit 0
		;;
	l)
		COMMAND=LIST
		;;
	p)
		COMMAND=PRINT_URL
		;;
	v)
		VOICE="$OPTARG"
		[[ "${VOICES["$OPTARG"]+_}" ]] || printf "Warning: Could not find '%s' in the list of voices\n" "$OPTARG" >&2
		;;
	d)
		COMMAND=DOWNLOAD
		OUTPUT="${OPTARG%.*}.ogg"
		OUTPUT_DIR="$(dirname "$OUTPUT")"
		[[ -d "$OUTPUT_DIR" ]] || {
			printf "Error: Output directory '%s' does not exist\n" "$OUTPUT_DIR" >&2
			exit 1
		}
		;;
	\?)
		printf "Error: Invalid option: '-%s'\n" "$OPTARG" >&2
		exit 1
		;;
	:)
		printf "Error: '-%s' requires an argument\n" "$OPTARG" >&2
		exit 1
		;;
	*)
		usage >&2
		exit 1
		;;
	esac
done
shift $((OPTIND - 1))
readonly COMMAND VOICE

# dispatch on command
case "$COMMAND" in
LIST)
	for voice in "${!VOICES[@]}"; do
		printf "%s\n" "$voice"
	done
	;;
*) # default, interact with API and download/print
	declare CURL_DATA HTTP_RESP API_ERROR SPEAK_URL
	# get text to send to API
	TEXT="$*"
	if [[ -z "$TEXT" ]]; then
		# print the log message if reading from STDIn
		# dont print if it the user is trying to capture the URL using the -p flag
		[[ "$COMMAND" != PRINT_URL ]] && echo "Reading text from STDIN..." >&2
		TEXT="$(cat)"
		readonly TEXT
	fi
	# encode JSON body
	CURL_DATA="$(jq -n --arg TTS_VOICE "$VOICE" --arg TTS_TEXT "$TEXT" '{"voice":$TTS_VOICE, "text":$TTS_TEXT}')" || exit $?
	# make request to StreamLabs
	HTTP_RESP="$(curl --silent -X POST --data "$CURL_DATA" -H 'Content-Type: application/json' 'https://streamlabs.com/polly/speak')" || exit $?
	# handle response
	API_ERROR="$(jq -r '.error' <<<"$HTTP_RESP")"
	if [[ "$API_ERROR" == null ]]; then # request succeeded
		SPEAK_URL="$(jq -r '.speak_url' <<<"$HTTP_RESP")"
		case "$COMMAND" in
		PRINT_URL)
			printf '%s\n' "$SPEAK_URL"
			;;
		*) # default, download to file
			if curl -s "$SPEAK_URL" --output "$OUTPUT"; then
				printf "Downloaded file to %s\n" "$OUTPUT"
			else
				printf 'Error downloading from %s\n' "$SPEAK_URL" >&2
				exit 1
			fi
			;;
		esac
	else
		printf 'API Error: %s\n' "$API_ERROR"
	fi
	;;
esac
